### PR TITLE
bleach-whitelist has been renamed bleach-allowlist

### PR DESCRIPTION
**Pull request by alikins**
Upstream package name has changed.

Issue: AAH-328

### CODE REVIEW

**Comment by alikins** [comment]
Not really tested yet...

**Review by awcrosby — APPROVED** [review]

**Comment by awcrosby** [comment]
Needs to have commits signed

**Comment by alikins** [comment]
@awcrosby 
> Needs to have commits signed

Updated

**Comment by awcrosby** [comment]
@alikins looks like a merge conflict after the last PR merged, since the lines edited are next to each other, I hate that haha

**Comment by alikins** [comment]
> @alikins looks like a merge conflict after the last PR merged, since the lines edited are next to each other, I hate that haha

Rebased

**Pull request merged**
