### PR TITLE
Accept file object and filename instead of path

### PR DESCRIPTION
**Pull request by awcrosby**
Related to https://github.com/ansible/galaxy-api/pull/78

### CODE REVIEW

**Comment by awcrosby** [comment]
@bmbouter I decided against ducktyping and changed from file path to file obj, if pulp_ansible still needs file path let me know and I will add it in

**Comment by bmbouter** [comment]
@awcrosby that sounds fine pulp_ansible can pass in the file handle [here](https://github.com/pulp/pulp_ansible/blob/master/pulp_ansible/app/tasks/collections.py#L110). Would you be able/willing to open a PR against pulp_ansible with that? You could use a `[noissue]` if you want to keep it easy since it's a small change.

Could that PR also have pulp_ansible's code use the newer version of process_collection? Right now that dep is brought in [here](https://github.com/pulp/pulp_ansible/blob/master/setup.py#L6). Either you could cut a pre-release and upgrade the version there to use it, or not cut a pre-release and have us switch to the master branch from your github directly (not from pypi). LMK if you want more details on that.

How does ^ sound so we can start using it soon?

**Comment by awcrosby** [comment]
@bmbouter I can make a PR for that…

Regarding pulp_ansible using the newer version of the process_collection - that is attempted in pulp_ansible#192 and currently blocked since some `test_sync` test collections don't pass importer validation, see https://github.com/pulp/pulp_ansible/pull/192#issuecomment-530190365 … I am trying to make the tests work around this while still keeping the test executing against a collection - but if you know a quicker way to get CI passing please let me know

**Comment by bmbouter** [comment]
@awcrosby oic. Yes let me see what I can do to help get those tests passing. Thank you for drawing the attention there.

**Pull request merged**
