### PR TITLE
Prevent fail-fast when running build-and-test

### PR DESCRIPTION
**Pull request by ssbarnea**
We only have 3 jobs running in the matrix and the default fail-fast
strategy makes it very hard to spot the failure cause, and impossible
to compare with others.

### CODE REVIEW

**Comment by awcrosby** [comment]
This PR looks good, but it needs an issue link or `No-Issue` on its own line in the commit to pass CI (since this is small `No-Issue` is fine)

**Comment by cidrblock** [comment]
I went to add the issue to keep this moving forward, but issues are not enabled for this project.

**Comment by thedoubl3j** [comment]
@cidrblock jira issue, not GH issue. but since this is small I would just `git commit --amend` and then on one of the commits, just pass `No-Issue`

**Comment by awcrosby** [comment]
@ssbarnea I don’t think adding a single line in a commit message is a deterrent. The commit simply needs `No-Issue` added in a single line, and all commits need to be signed.

**Pull request closed without merging**
